pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'from alpine' }
      }
      steps {
        echo 'Welcome to Goa Singham!!!'
        sh 'mvn --version'
      }
    }
   
    }
  }

