pipeline{
  agent none
  parameters{
    string(name:'VERSION', defaultValue: '1.1.1', description: 'Version-Info')
    booleanParam(name: 'VALUE', defaultValue: true, description: 'Boolean value')
  }
  stages{
    stage('Backend'){
      agent any
      when{
        expression{
            params.VALUE
        }
      }
      steps{
          echo 'VALUE is True'
          echo 'Welcome to Goa Singham!!!'
      }
  }
}
}
