pipeline{
  agent any
  parameters{
    string(name: 'namePlease', defaultValue: 'Jay-Bhim Kambale', description: 'Jayanti Vishesh')
    booleanParam(name: 'version', defaultValue: true, description: 'Lage raho')
  }
  stages{
    stage('build'){
      when{
        expression{
          params.namePlease = 'Jay-Bhim Kambale'
        }
      }
      steps{
          echo "Welcome ${NamePlease} Bhau!!!"
          //echo 'Savinay Jay-Bhim!!!'
      }
    }
  }
}
